### ISSUE TITLE
keyrings/debian-ports-archive-keyring.gpg may be incorrect or out of date

### ISSUE THREAD

**Issue by xushengrui02** [xzhangxa/debian-riscv#1]
你好，按照你文档里面说的步骤更新了debian-ports-archive-keyring.gpg
但是问题还是没有解决；
![image](https://user-images.githubusercontent.com/89174926/233846974-bc3414d1-9465-4841-a879-a0c3aced8e74.png)
能帮忙看看嘛

**Comment by xzhangxa** [comment]
Hi @xushengrui02 

我没有直接去动gpg文件，都是装deb的，你这里显示的包名是自己改过？Debian自己的包命名不是这样的。

之前的keyring过期了，我在master里更新了脚本去下最新的包，在Ubuntu 20.04上测了没问题。你可以试一下。

```
...
I: Retrieving InRelease
I: Checking Release signature
I: Valid Release signature (key id 01C2D6F3D1A46AD1C0DC2F3D8D69674688B6CB36)
I: Retrieving Packages
I: Validating Packages
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...
I: Checking component main on http://deb.debian.org/debian-ports...
I: Retrieving adduser 3.132
...
```

**Comment by xzhangxa** [comment]
我更新了下别的内容，force push了master。

**Comment by xushengrui02** [comment]
> Hi @xushengrui02
> 
> 我没有直接去动gpg文件，都是装deb的，你这里显示的包名是自己改过？Debian自己的包命名不是这样的。
> 
> 之前的keyring过期了，我在master里更新了脚本去下最新的包，在Ubuntu 20.04上测了没问题。你可以试一下。
> 
> ```
> ...
> I: Retrieving InRelease
> I: Checking Release signature
> I: Valid Release signature (key id 01C2D6F3D1A46AD1C0DC2F3D8D69674688B6CB36)
> I: Retrieving Packages
> I: Validating Packages
> I: Resolving dependencies of required packages...
> I: Resolving dependencies of base packages...
> I: Checking component main on http://deb.debian.org/debian-ports...
> I: Retrieving adduser 3.132
> ...
> ```
好的，感谢，感谢；
